# Generated by Django 3.2.8 on 2021-10-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='definition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='image_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='term',
            field=models.TextField(),
        ),
    ]
