# Generated by Django 3.2.8 on 2021-10-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_alter_flashcard_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author_id', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=511)),
                ('stars', models.IntegerField(default=0)),
            ],
        ),
    ]
