# Generated by Django 3.2.8 on 2021-10-16 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='deck_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flashcards.deck'),
            preserve_default=False,
        ),
    ]
