# Generated by Django 3.2.8 on 2021-10-16 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_flashcard_deck_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='deck_id',
            new_name='deck',
        ),
    ]
